apiVersion: v2
name: ocs-operator
appVersion: "1.1"
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
dependencies:
  - name: ocs-operator
    version: 0.1.0
    repository: https://charts.cloudnativetoolkit.dev
